#
# Created by Nikita Zarudniy on 6/29/2023.
#

set(LIBRARY_NAME ${PROJECT_NAME})
set(LIBRARY_TARGET_NAME "${LIBRARY_NAME}_lib")

find_package(OpenGL REQUIRED)

add_compile_definitions(SPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE)

#TODO: Replace this with KROG_API exports
#set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

# Krog Library Target

add_library(${LIBRARY_TARGET_NAME} STATIC)

target_precompile_headers(${LIBRARY_TARGET_NAME} PRIVATE "$<$<COMPILE_LANGUAGE:CXX>:${CMAKE_CURRENT_SOURCE_DIR}/pch.h>")

target_compile_definitions(${LIBRARY_TARGET_NAME} PRIVATE KROG_EXPORT NOMINMAX)
target_include_directories(${LIBRARY_TARGET_NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
set_target_properties(${LIBRARY_TARGET_NAME} PROPERTIES OUTPUT_NAME "lib${PROJECT_NAME}")

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/../cmake/includes/kr_appname.h.in ${CMAKE_CURRENT_BINARY_DIR}/generated/kr_appname.h)
target_include_directories(${LIBRARY_TARGET_NAME} PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/generated)

set(HEADERS
        krog/common.h
        krog/application.h
        krog/util/loggable.h
        krog/util/framesynchronizer.h
        krog/util/persistentconfig.h
        krog/util/threadwrapper.h
        krog/util/imageloader.h
        krog/util/filesystem.h
        krog/util/physfs.hpp

        krog/renderer/formats.h
        krog/renderer/window.h
        krog/renderer/image.h
        krog/renderer/imagestream.h
        krog/renderer/texture.h
        krog/events/event.h
        krog/events/eventbus.h
        krog/events/windowevents.h

        krog/ui/layer.h
        krog/ui/imguilayer.h

        krog/video/capture.h
        $<$<BOOL:${KR_USE_AV}>:krog/video/avcapture.h> # TODO: Fill correct sources

        krog/ui/misc/imgui_spectrum.h)

set(SOURCES
        krog/application.cc
        krog/util/loggable.cc
        krog/util/framesynchronizer.cc
        krog/util/persistentconfig.cc
        krog/util/threadwrapper.cc
        krog/util/physfs.cc
        krog/util/filesystem_common.cc
        $<$<BOOL:${WIN32}>:krog/util/filesystem_win32.cc>
        $<$<BOOL:${UNIX}>:krog/util/filesystem_unix.cc>

        krog/renderer/formats.cc
        krog/renderer/window.cc
        krog/renderer/image.cc
        krog/renderer/imagestream.cc
        krog/renderer/texture.cc
        krog/events/eventbus.cc

        krog/ui/layer.cc
        krog/ui/imguilayer.cc

        krog/video/capture.cc
        $<$<BOOL:${KR_USE_AV}>:krog/video/avcapture.cc> # TODO: Fill correct sources

        krog/ui/misc/imgui_spectrum.cc)

target_sources(${LIBRARY_TARGET_NAME} PRIVATE ${HEADERS} ${SOURCES})

target_link_libraries(${LIBRARY_TARGET_NAME} PUBLIC
        fmt::fmt
        yaml-cpp
        spdlog::spdlog
        eventpp::eventpp
        glm::glm
        Glad::Glad
        OpenGL::GL
        SDL3::SDL3
        PhysFS::PhysFS-static
        ImGui::ImGui
        STB::Image
        $<$<BOOL:${KR_USE_AV}>:${FFMPEG_TARGETS}>)

add_library(Krog::Krog ALIAS ${LIBRARY_TARGET_NAME})

# Asset baking
set(ASSETS_DIR "${KR_SOURCE_DIR}/assets")
set(ARCHIVE_PATH "data/engine.pak")
cmake_path(APPEND KR_RUNTIME_OUTPUT_DIR "data" OUTPUT_VARIABLE DATA_PATH)
cmake_path(APPEND KR_RUNTIME_OUTPUT_DIR ${ARCHIVE_PATH} OUTPUT_VARIABLE OUTPUT_ARCHIVE)

file(GLOB_RECURSE ASSET_FILES
        RELATIVE "${ASSETS_DIR}"
        CONFIGURE_DEPENDS
        "${ASSETS_DIR}/*"
)

list(FILTER ASSET_FILES EXCLUDE REGEX "/$")

# Generate asset info header
set(GENERATED_HEADER "${CMAKE_CURRENT_BINARY_DIR}/generated/kr_assets.h")

file(WRITE ${GENERATED_HEADER} "// This file is auto-generated by CMake\n")
file(APPEND ${GENERATED_HEADER} "#ifndef KR_ASSETS_H\n")
file(APPEND ${GENERATED_HEADER} "#define KR_ASSETS_H\n\n")

file(APPEND ${GENERATED_HEADER} "#define KR_ARCHIVE_FILE \"${ARCHIVE_PATH}\"\n")

set(FILE_PATHS)

foreach(ASSET_PATH ${ASSET_FILES})
    string(REPLACE "/" "_" MACRO_NAME ${ASSET_PATH})
    string(REPLACE "." "_" MACRO_NAME ${MACRO_NAME})
    string(REPLACE "-" "_" MACRO_NAME ${MACRO_NAME})
    string(TOUPPER ${MACRO_NAME} MACRO_NAME)
    set(MACRO_NAME "ASSET_${MACRO_NAME}")

    file(APPEND ${GENERATED_HEADER} "#define ${MACRO_NAME} \"${ASSET_PATH}\"\n")

    list(APPEND FILE_PATHS "${ASSETS_DIR}/${ASSET_PATH}")
endforeach()

file(APPEND ${GENERATED_HEADER} "\n#endif // KR_ASSETS_H\n")

# Create archive file
add_custom_command(
        TARGET ${LIBRARY_TARGET_NAME} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E make_directory "${DATA_PATH}"
        COMMAND ${CMAKE_COMMAND} -E tar cfv "${OUTPUT_ARCHIVE}" --format=zip -- ${FILE_PATHS}
        WORKING_DIRECTORY "${ASSETS_DIR}"
        COMMENT "Creating archive: ${OUTPUT_ARCHIVE}"
)

message(STATUS "Krog assets archive will be created at: ${OUTPUT_ARCHIVE}")
